9.8. Помощь друга
htmlacademy-javascript/2040395-kekstagram-27 pull request #8
Opened 2022-11-05 22:21 UTC by Kskroha

2022-11-05 23:10 UTC, AlexMasterov requested changes

2022-11-05 23:10 UTC, AlexMasterov commented on js/effects.js
> +const sliderElement = document.querySelector('.effect-level__slider');
const slider`Element` = document.querySelector('.effect-level__slider');

Нужно здесь из названия убрать `Element` или добавить его в названия _всех_ переменных проекта, которые указывают на DOM-элементы (= объекты типа [`Element`](https://developer.mozilla.org/ru/docs/Web/API/Element)).

[`Д 6`](https://up.htmlacademy.ru/javascript/27/criteries#d6)
> Используется единый стиль именования переменных

> если переменные, которые хранят DOM-элемент, содержат слово `Element` или любое другое, но одно и то же везде

2022-11-05 23:10 UTC, AlexMasterov commented on js/form.js
> +  value.trim();
См. [String.p.`trim`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/Trim#%D0%BE%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5):
> **Метод возвращает строку** с вырезанными пробельными символами с её концов. **Метод не изменяет значение самой строки**

2022-11-05 23:10 UTC, AlexMasterov commented on js/form.js
> +  return tags.every((tag) => tag.trim().length <= 20);
return tags.every((tag) => tag.trim().length <= `20`);

[`Д 19`](https://up.htmlacademy.ru/javascript/27/criteries#d19) 
> В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа

2022-11-05 23:10 UTC, AlexMasterov commented on js/scale.js
> +const getScaleValue = (n = 1) => {
const getScaleValue = (`n` = 1) => {

На защите проекта _могут_ придраться.

[`Б 4`](https://up.htmlacademy.ru/javascript/27/criteries#b4)
> В качестве имён переменных и свойств используются английские существительные

> Сокращения в словах запрещены

2022-11-05 23:10 UTC, AlexMasterov commented on js/effects.js
> +const DEFAULT_EFFECT = EFFECTS[0];
<details>
<summary>effects.js</summary>

https://github.com/htmlacademy-javascript/2040395-kekstagram-27/blob/78ed68f5f3484cdf3f1ad824b527cec439d5eee6/js/effects.js#L6
https://github.com/htmlacademy-javascript/2040395-kekstagram-27/blob/78ed68f5f3484cdf3f1ad824b527cec439d5eee6/js/effects.js#L55
</details>

[`Б 10`](https://up.htmlacademy.ru/javascript/27/criteries#b10) 
> Список констант идёт перед основным кодом

2022-11-05 23:10 UTC, AlexMasterov commented on js/effects.js
> +  }
<details>
<summary>effects.js</summary>

https://github.com/htmlacademy-javascript/2040395-kekstagram-27/blob/78ed68f5f3484cdf3f1ad824b527cec439d5eee6/js/effects.js#L70-L76
</details>

На защите проекта _могут_ придраться.

[`Д 23`](https://up.htmlacademy.ru/javascript/27/criteries#d23) 
> Изменения применяются точечно

2022-11-05 23:10 UTC, AlexMasterov commented on js/effects.js
> +const isDefault = () => chosenEffect === DEFAULT_EFFECT;
const `isDefault` = () => chosenEffect === DEFAULT_`EFFECT`;

Желательно уточнить название функции.

[`Б 6`](https://up.htmlacademy.ru/javascript/27/criteries#b6)
> Название функции или метода должно быть глаголом и соответствовать действию, которое выполняет функция или метод

2022-11-05 23:10 UTC, AlexMasterov commented on js/effects.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/200144146-7ada9f38-b2f4-4e71-bbff-34809c027545.png)

</details>

См. ТЗ:
> Значение по умолчанию — `100%`

2022-11-05 23:10 UTC, AlexMasterov commented on js/form.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/200144255-4c88324f-3b2a-4215-b954-4b4caddeb415.png)

</details>

См. ТЗ:
> хэш-теги необязательны

2022-11-05 23:10 UTC, AlexMasterov commented on js/form.js
> +const VALID_SYMBOLS = /^#[a-zа-яё0-9]/i;
const `VALID_SYMBOLS` = /^#[a-zа-яё0-9]/i;

На защите _могут_ придраться, причем в обе стороны, по разным критериям.

[`Б 3`](https://up.htmlacademy.ru/javascript/27/criteries#b3)
> Названия переменных, параметров, свойств и методов начинаются со строчной буквы и записываются в нотации `camelCase`

2022-11-05 23:10 UTC, AlexMasterov commented on js/form.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/200145159-4c7a2021-e91b-4115-bbcb-2f7d086853c6.png)

</details>

Если окно для загрузки фото закрыть нажатием на кнопку (крестик), то остается глобальный обработчик на `document` для `keydown`.

[`Б 26`](https://up.htmlacademy.ru/javascript/27/criteries#b26)
> Обработчики событий добавляются и удаляются своевременно

2022-11-11 12:35 UTC, ksundelife requested changes
Приветствую.
Ксюша, большие шаги на пути к успеху сделаны и весьма успешно.
Запишу видео-разбор на примере, как понятно и пошагово структурировать логику выполнения модуля за модулем.
Проработаем разбиение на модули и разделение ответственности.

Работа заметно преобразится.

До встречи в личных сообщениях.

2022-11-13 17:47 UTC, ksundelife approved these changes

2022-11-13 17:47 UTC, merged